export const mockColleges = [
  {
    id: 1,
    name: "Delhi Technological University",
    location: "Delhi, India",
    courses: [
      "B.Tech Computer Science",
      "B.Tech Mechanical Engineering",
      "B.Tech Electrical Engineering",
      "B.Tech Civil Engineering",
    ],
    fees: "₹2.5 Lakhs/year",
    rating: 4.2,
    established: 1941,
    campus: "Main Campus, Delhi",
    highlights: [
      "NAAC A Grade",
      "Placement Rate: 85%",
      "Industry Partnerships",
    ],
  },
  {
    id: 2,
    name: "Indian Institute of Technology Delhi",
    location: "Delhi, India",
    courses: [
      "B.Tech Computer Science",
      "B.Tech Electrical Engineering",
      "B.Tech Mechanical Engineering",
      "B.Tech Chemical Engineering",
    ],
    fees: "₹8 Lakhs/year",
    rating: 4.8,
    established: 1961,
    campus: "Hauz Khas, Delhi",
    highlights: [
      "IIT Premier Institute",
      "Research Focus",
      "Top Recruiters: Google, Microsoft",
    ],
  },
  {
    id: 3,
    name: "Netaji Subhas University of Technology",
    location: "Delhi, India",
    courses: [
      "B.Tech Information Technology",
      "B.Tech Biotechnology",
      "B.Tech Electronics and Communication",
      "B.Tech Computer Engineering",
    ],
    fees: "₹3 Lakhs/year",
    rating: 4.1,
    established: 1983,
    campus: "Dwarka, Delhi",
    highlights: [
      "AICTE Approved",
      "Modern Infrastructure",
      "Strong Alumni Network",
    ],
  },
  {
    id: 4,
    name: "Jamia Millia Islamia",
    location: "Delhi, India",
    courses: [
      "B.Tech Civil Engineering",
      "B.Architecture",
      "B.Tech Mechanical Engineering",
      "B.Tech Electrical Engineering",
    ],
    fees: "₹1.8 Lakhs/year",
    rating: 4.0,
    established: 1920,
    campus: "Jamia Nagar, Delhi",
    highlights: [
      "Central University",
      "Diverse Student Community",
      "Heritage Campus",
    ],
  },
  {
    id: 5,
    name: "Indraprastha Institute of Information Technology",
    location: "Delhi, India",
    courses: [
      "B.Tech Computer Science",
      "B.Tech Electronics and Communication",
      "B.Tech Computational Mathematics",
      "B.Des",
    ],
    fees: "₹4 Lakhs/year",
    rating: 4.3,
    established: 2008,
    campus: "Okhla, Delhi",
    highlights: ["IIIT Delhi", "Focus on IT Education", "Startup Incubator"],
  },
  {
    id: 6,
    name: "Amity University",
    location: "Noida, Uttar Pradesh",
    courses: [
      "B.Tech Computer Science",
      "B.Tech Artificial Intelligence",
      "B.Tech Data Science",
      "B.Tech Robotics",
    ],
    fees: "₹4.5 Lakhs/year",
    rating: 3.9,
    established: 2005,
    campus: "Noida Campus",
    highlights: [
      "Private University",
      "International Collaborations",
      "Modern Facilities",
    ],
  },
  {
    id: 7,
    name: "Vellore Institute of Technology",
    location: "Vellore, Tamil Nadu",
    courses: [
      "B.Tech CSE",
      "B.Tech IT",
      "B.Tech Biotechnology",
      "B.Tech Mechanical",
    ],
    fees: "₹7.8 Lakhs/year",
    rating: 4.4,
    established: 1984,
    campus: "Vellore Campus",
    highlights: ["Deemed University", "Strong Placements", "Research Programs"],
  },
];
